services:
  log-telebot:
    environment:
      - TZ=Europe/Moscow
    image: imediadev/log-telebot
    user: "1002:1002"
    env_file: .env
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - /home/egor/project:/home/egor/project
      - /home/egor/bots:/home/egor/bots
